language: ruby
cache: bundler
matrix:
  include:
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set=centos7
    script: bundle exec rake all beaker
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set=xenial
    script: bundle exec rake all beaker
