language: ruby
cache: bundler
matrix:
  include:
  - rvm: 2.3.0
    env: PUPPET_VERSION='~> 3.8.0'
    script: bundle exec rake all
  - rvm: 2.3.0
    env: PUPPET_VERSION='~> 4.4.0'
    script: bundle exec rake all
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set=centos7
    script: bundle exec rake beaker
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set=jessie
    script: bundle exec rake beaker
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set=xenial
    script: bundle exec rake beaker
notifications:
  slack:
    secure: KKgbH1QeviNCKQOrPj66igMODotgqqM42ENX6PHgnjx4kxeDYkTak1U6BZPW1U9CVIlhwOjSr7CvOh3w2nYx7WCht0JHsUT8bvM1BdDAp3Odqo++nYRhUpAgWC2CELfa2feIDgxiHVxZqAX9TSoVpMKQ57nt4mmuGHEOj7C6fSQ/DWHQXjnnFQTEydEtyiZUJnol+VfJ1oN+TgL7fJv7xD2Ki9Dv4/vff2NlxCjh6gMO9u8CATZcvTji4XFydj52AJDMuXxhPOV4jyiGemmkVig6VR3xPJSD+vkLwc5HN86t9/soddO6Ep7KkuhNHw2AMfLn8vRBpIGyqHURmyg0/0Yd4q1ASptJvtbpTDP6c7yhYI0zgg8Qvy4y8syLt0vZwCukFJ2X87fknxYCPFTaqprNg+aKWdtCcrASlZRGb5yZYpAnlqsNMAunNxC94BrGn9nKATx8yY9TTPnBxcO1Znf/DKyNZslE3OBa09U9P/SdJsQRGLOLCOzep8URgwaMNr1CG3p49JZQMJXIdyhuspNeHdALKIYWONLKpNItaeM32zmzmaLL7HCfafEIUvnXUg6iSuCcBuFbmhIcETM3+PQ5hcBRvG6aZvAhCyzYg0NqqQU3K9V7in/ZCngXndzz45lrnV2v/cC7GD4F5oWCJzec3WlFY5Z5wetFLG6HRBA=
