language: ruby
cache: bundler
matrix:
  include:
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set=centos7 BEAKER_debug=true
    script: bundle exec rake all beaker
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set=xenial BEAKER_debug=true
    script: bundle exec rake all beaker
